### ISSUE TITLE
Jenkings build failure for React Native application

### ISSUE THREAD

**Issue by ldco2016** [microsoft/appcenter-sampleapp-react-native#14]
I am trying to understand the significance of the `appcenter-config.json` file in relation to this error message I keep getting in the Jenkins build:

```
BUILD FAILED in 16s

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ENGAGE_ENDPOINT=dv APPCENTER_KEY=<this-key-references-in-scripts-android-build> ENGAGE_VERSION=3.6.2-1854 APPCENTER_PLATFORM=android npm run setup && cd android && ./gradlew assembleDevRelease -PversionName=3.6.2-1854 -PversionCode=1854 && cd ..' }
============================= Copying APK to Dist =============================
nps is executing `ios.build` : node node_modules/rimraf/bin.js dist/*.ipa && babel-node scripts/ios/build.js
############################# DEV Build IOS Start #############################
ENGAGE_ENDPOINT=dv APPCENTER_KEY=<this-key-references-in-scripts-ios-build> ENGAGE_VERSION=3.6.2-1854 APPCENTER_PLATFORM=ios npm run setup && xcodebuild -workspace ios/NFIBEngage.xcworkspace -configuration Release -scheme DEV -derivedDataPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive archive -UseModernBuildSystem=NO && xcodebuild -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive -exportPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/dist -exportOptionsPlist /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/dev.plist -exportArchive
** ARCHIVE FAILED **


The following build commands failed:
	Ld build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/NFIBEngage.build/Release-iphoneos/DEV.build/Objects-normal/arm64/DEV normal arm64
	Ld build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/NFIBEngage.build/Release-iphoneos/DEV.build/Objects-normal/armv7/DEV normal armv7
(2 failures)
child_process.js:526
    throw err;
    ^

Error: Command failed: ENGAGE_ENDPOINT=dv APPCENTER_KEY=<this-key-references-in-scripts-ios-build> ENGAGE_VERSION=3.6.2-1854 APPCENTER_PLATFORM=ios npm run setup && xcodebuild -workspace ios/NFIBEngage.xcworkspace -configuration Release -scheme DEV -derivedDataPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive archive -UseModernBuildSystem=NO && xcodebuild -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive -exportPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/dist -exportOptionsPlist /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/dev.plist -exportArchive
** ARCHIVE FAILED **


The following build commands failed:
	Ld build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/NFIBEngage.build/Release-iphoneos/DEV.build/Objects-normal/arm64/DEV normal arm64
	Ld build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/NFIBEngage.build/Release-iphoneos/DEV.build/Objects-normal/armv7/DEV normal armv7
(2 failures)

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:155:5
    at Array.forEach (native)
    at run (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:117:16)
    at Object.<anonymous> (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:166:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
The script called "ios.build" which runs "node node_modules/rimraf/bin.js dist/*.ipa && babel-node scripts/ios/build.js" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "build" which runs "nps android.build && nps ios.build && nps finish" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by vyasknellutla** [comment]
Hi @ldco2016,

Terribly sorry for the delay, we've recently went through an overhaul of each of our sample applications. Would you mind trying out the latest version of this repository?

**Comment by vyasknellutla** [comment]
Hi @ldco2016,

I believe the latest version of this repository should resolve any issues you were running into previously, if you're still experiencing issues please reach out to us via support (the blue circle button in the bottom right corner of App Center) so we can better investigate the problem.
